filename = [app.appname 'out_t' num2str(itime)];
fn = ['app/' filename];
tmp = getsolution(fn, mpiprocs, size(UDG,1), app.ncu, elempart);
UDG(:,1:4,:)=tmp;
app.runmode=1;
app.dt=0;
app = preprocessing(app,mesh.p,mesh.t,mesh.dgnodes,UDG,ODG,[],mesh.bndexpr,periodicexpr,0,0);
mkdir('app');
movefile('*.bin','app');
probsol;
filename = [app.appname 'out'];
fn = ['app/' filename];
tmp = getsolution(fn, mpiprocs, size(UDG,1), app.nc, elempart);
