// Auto-generated by apps/library_example/port_codegen.sh.
// Math is in my_model.hpp (auto-generated by retargeted text2code).
// Boilerplate is in <exasim/run.hpp>.

#include <exasim/run.hpp>
#include "my_model.hpp"

int main(int argc, char** argv) {
    return exasim::run<GeneratedModel>(argc, argv);
}
