// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
#include <exasim/model.hpp>

struct GeneratedModel : exasim::ModelDefaults<GeneratedModel> {
    static constexpr int nd     = 3;
    static constexpr int ncu    = 1;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 0;
    static constexpr int nparam = 2;
    static constexpr auto disc  = exasim::Discretization::HDG;
    static constexpr int Nq = ncu * (1 + nd);

    KOKKOS_INLINE_FUNCTION static
    void flux(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];
        const double mu0 = mu[0];

        f[0] = uq1*mu0;
        f[1] = uq2*mu0;
        f[2] = uq3*mu0;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double x0 = x[0];
        const double x1 = x[1];
        const double x2 = x[2];

        f[0] = 3*pow(acos(-1), 2)*sin(acos(-1)*x2)*sin(acos(-1)*x1)*sin(acos(-1)*x0);
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {

        f[0] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];

        f[0] = uq0;
        f[1] = uq1 + uq2 + uq3;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];

        f[0] = uq1;
        f[1] = uq2;
        f[2] = uq3;
    }

    KOKKOS_INLINE_FUNCTION static
    void qoi_volume(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double x0 = x[0];
        const double x1 = x[1];
        const double x2 = x[2];
        const double uq0 = uq[0];

        f[0] = pow(uq0 - sin(acos(-1)*x2)*sin(acos(-1)*x1)*sin(acos(-1)*x0), 2);
        f[1] = uq0;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(double f[], const double x[], const double uinf[], const double mu[]) {

        f[0] = 0.0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(double f[], int ib, const double x[], const double uq[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {
            const double uq0 = uq[0];
            const double uq1 = uq[1];
            const double uq2 = uq[2];
            const double uq3 = uq[3];
            const double uhat0 = uh[0];
            const double n0 = n[0];
            const double n1 = n[1];
            const double n2 = n[2];
            const double tau0 = tau[0];
            const double mu0 = mu[0];

            f[0] = tau0*(-uhat0 + uq0) + n0*uq1*mu0 + n1*uq2*mu0 + n2*uq3*mu0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(double f[], int ib, const double x[], const double uq[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = 0.0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(double f[], int ib, const double x[], const double uq[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {
            const double uhat0 = uh[0];
            const double tau0 = tau[0];

            f[0] = -tau0*uhat0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {
        const double mu0 = mu[0];

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = mu0;
        f[4] = 0;
        f[5] = 0;
        f[6] = 0;
        f[7] = mu0;
        f[8] = 0;
        f[9] = 0;
        f[10] = 0;
        f[11] = mu0;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(double f[], const double x[], const double uq[], const double w[], const double mu[], const double uinf[], double t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
        f[3] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(double f[], int ib, const double x[], const double uq[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(double f[], int ib, const double x[], const double uq[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {
            const double tau0 = tau[0];

            f[0] = -tau0;
        }
    }

};
