// Tutorial path 02 — codegen Model + legacy CLI driver.
//
// `my_model.hpp` is generated by `text2code` from `pdemodel.txt`.
// `main.cpp` is the same three-line entry point as the hand-written
// CLI path, with the templated model swapped from `Poisson2D` to
// the auto-generated `GeneratedModel`.

#include <exasim/run.hpp>
#include "my_model.hpp"

int main(int argc, char** argv) {
    return exasim::run<GeneratedModel>(argc, argv);
}
