// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
struct PdeModel : ModelDefaults<PdeModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 1;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 0;
    static constexpr int nparam = 1;
    static constexpr int Nq = ncu * (1 + nd);

    KOKKOS_INLINE_FUNCTION static
    void flux(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];
        const dstype mu0 = mu[0];

        f[0] = uq1*mu0;
        f[1] = uq2*mu0;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x0 = x[0];
        const dstype x1 = x[1];

        f[0] = 2*Kokkos::pow(Kokkos::acos(-1), 2)*Kokkos::sin(Kokkos::acos(-1)*x1)*Kokkos::sin(Kokkos::acos(-1)*x0);
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq0 = uq[0];
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];

        f[0] = uq0;
        f[1] = uq1 + uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype uq1 = uq[1];
        const dstype uq2 = uq[2];

        f[0] = uq1;
        f[1] = uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void qoi_volume(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype x0 = x[0];
        const dstype x1 = x[1];
        const dstype uq0 = uq[0];

        f[0] = Kokkos::pow(uq0 - Kokkos::sin(Kokkos::acos(-1)*x1)*Kokkos::sin(Kokkos::acos(-1)*x0), 2);
        f[1] = uq0;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(dstype f[], const dstype x[], const dstype uinf[], const dstype mu[]) {

        f[0] = 0.0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uhat0 = uh[0];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype mu0 = mu[0];

            f[0] = tau0*(-uhat0 + uq0) + n0*uq1*mu0 + n1*uq2*mu0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0.0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uhat0 = uh[0];
            const dstype tau0 = tau[0];

            f[0] = -tau0*uhat0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void qoi_boundary(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype uq0 = uq[0];
            const dstype uq1 = uq[1];
            const dstype uq2 = uq[2];
            const dstype uhat0 = uh[0];
            const dstype n0 = n[0];
            const dstype n1 = n[1];
            const dstype tau0 = tau[0];
            const dstype mu0 = mu[0];

            f[0] = tau0*(-uhat0 + uq0) + n0*uq1*mu0 + n1*uq2*mu0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {
        const dstype mu0 = mu[0];

        f[0] = 0;
        f[1] = 0;
        f[2] = mu0;
        f[3] = 0;
        f[4] = 0;
        f[5] = mu0;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(dstype f[], const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype mu[], const dstype uinf[], dstype t) {

        f[0] = 0;
        f[1] = 0;
        f[2] = 0;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(dstype f[], int ib, const dstype x[], const dstype uq[], const dstype v[], const dstype w[], const dstype uh[], const dstype n[], const dstype tau[], const dstype mu[], const dstype uinf[], dstype t) {
        if (ib == 1) {
            const dstype tau0 = tau[0];

            f[0] = -tau0;
        }
    }

};
