// Tutorial path 03 — codegen Model + legacy CLI driver.
//
// `my_model.hpp` is generated by `text2code` from `pdemodel.txt`.
// `main.cpp` is the same three-line entry point as path 01, with
// the templated model swapped from the hand-written `Poisson2D`
// to the auto-generated `GeneratedModel`.

#include <exasim/run.hpp>
#include "my_model.hpp"

int main(int argc, char** argv) {
    return exasim::run<GeneratedModel>(argc, argv);
}
