// Tutorial path 04 — codegen Model + ExasimSolver<M>::load_pdeapp.
//
// `my_model.hpp` is generated by `text2code` from `pdemodel.txt`
// (the same input used by path 03). `main.cpp` constructs an
// `ExasimSolver<GeneratedModel>` and calls `load_pdeapp(argv[1])`,
// which parses `pdeapp.txt` itself, runs preprocessing, and stages
// the runtime so the call to `solve()` produces the converged
// solution.

#include <exasim/run.hpp>
#include <exasim/solver_facade.hpp>
#include <exasim/model.hpp>

#include "my_model.hpp"

#include <cstdio>

int main(int argc, char** argv) {
    int mpiprocs = 1, mpirank = 0, shmrank = 0;
#ifdef HAVE_MPI
    MPI_Init(&argc, &argv);
    EXASIM_COMM_WORLD = MPI_COMM_WORLD;
    EXASIM_COMM_LOCAL = MPI_COMM_WORLD;
    MPI_Comm_size(EXASIM_COMM_WORLD, &mpiprocs);
    MPI_Comm_rank(EXASIM_COMM_WORLD, &mpirank);
    MPI_Comm shmcomm;
    MPI_Comm_split_type(EXASIM_COMM_WORLD, MPI_COMM_TYPE_SHARED, 0,
                        MPI_INFO_NULL, &shmcomm);
    MPI_Comm_rank(shmcomm, &shmrank);
#endif
#ifdef HAVE_CUDA
    int nd; cudaGetDeviceCount(&nd); cudaSetDevice(shmrank % nd);
#endif
#ifdef HAVE_HIP
    int nd; hipGetDeviceCount(&nd); hipSetDevice(shmrank % nd);
#endif
    (void)shmrank;

    if (argc < 2) {
        if (mpirank == 0) std::fprintf(stderr, "Usage: %s pdeapp.txt\n", argv[0]);
#ifdef HAVE_MPI
        MPI_Finalize();
#endif
        return 1;
    }

    Kokkos::initialize();
    {
        exasim::ExasimSolver<GeneratedModel> solver;
        solver.pde().saveOutputs = 1;
        solver.load_pdeapp(argv[1], mpirank);
        solver.solve(mpiprocs, mpirank);
    }
    Kokkos::finalize();
#ifdef HAVE_MPI
    MPI_Finalize();
#endif
    return 0;
}
