function boundaryexpr = boundaryexpr_primitives_example(ymin, zmin, xmax)
%BOUNDARYEXPR_PRIMITIVES_EXAMPLE Example boundary expressions using helpers.
%   boundaryexpr = boundaryexpr_primitives_example(ymin, zmin, xmax)

tol = 1e-6;

boundaryexpr = { ...
    @(p) bnd_plane(p, [2, ymin, tol]), ...
    @(p) bnd_plane(p, [3, zmin, tol]), ...
    @(p) bnd_plane(p, [3, xmax, tol]), ...
    @(p) bnd_or(bnd_lt(p, [1, -1e-3]), bnd_gt(p, [2, 0.1])), ...
    @(p) bnd_and(bnd_ge(p, [1, -20, tol]), bnd_le(p, [1, 20, tol])) ...
};

% If the third boundary is intended to be x = xmax, use:
% @(p) bnd_plane(p, [1, xmax, tol])
end
