// Auto-generated by text2code. Do not edit by hand.
// Regenerate with `text2code <pdeapp.txt>`.
//
// This header is consumed by `<exasim/model.hpp>`'s templated FEM
// internals. The struct below satisfies the Model contract; the
// inherited `ModelDefaults<GeneratedModel>` supplies zero-fill
// defaults for any optional method this PDE doesn't define.
#pragma once

#include <Kokkos_Core.hpp>
#include <exasim/model.hpp>

struct GeneratedModel : exasim::ModelDefaults<GeneratedModel> {
    static constexpr int nd     = 2;
    static constexpr int ncu    = 4;
    static constexpr int ncw    = 0;
    static constexpr int nco    = 1;
    static constexpr int nparam = 11;
    static constexpr auto disc  = exasim::Discretization::HDG;
    static constexpr int Nq = ncu * (1 + nd);

    KOKKOS_INLINE_FUNCTION static
    void flux(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double x1 = x[1];
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];
        const double uq4 = uq[4];
        const double uq5 = uq[5];
        const double uq6 = uq[6];
        const double uq7 = uq[7];
        const double uq8 = uq[8];
        const double uq9 = uq[9];
        const double uq10 = uq[10];
        const double uq11 = uq[11];
        const double v0 = v[0];
        const double mu0 = mu[0];
        const double mu1 = mu[1];
        const double mu2 = mu[2];
        const double mu3 = mu[3];
        const double mu9 = mu[9];

        const double x0 = pow(uq1, 2);
        const double x2 = pow(uq0, -1);
        const double x3 = -1.0 + mu0;
        const double x4 = pow(uq2, 2);
        const double x5 = pow(uq0, -2);
        const double x6 = 0.5*(x0*x5 + x4*x5);
        const double x7 = uq3 - x6*uq0;
        const double x8 = x3*x7;
        const double x9 = x2*uq2;
        const double x10 = x9/x1;
        const double x11 = x2*uq1;
        const double x12 = uq5 - uq4*x11;
        const double x13 = x2*x12;
        const double x14 = uq10 - x9*uq8;
        const double x15 = x2*x14;
        const double x16 = x2*x8;
        const double x17 = (110.4 + mu9)*sqrt(pow(x3, 3)*pow(x7, 3)*pow(mu3, 6)*pow(mu0, 3)/pow(uq0, 3))/(mu1*(110.4 + 1.0*x16*pow(mu3, 2)*mu9*mu0));
        const double x18 = 0.666666666666667*x17;
        const double x19 = x18*(x10 + 2*x13 - x15);
        const double x20 = uq6 - x9*uq4;
        const double x21 = uq9 - uq8*x11;
        const double x22 = 1.0*x17;
        const double x23 = (x2*x20 + x2*x21)*x22;
        const double x24 = x23 + x9*uq1;
        const double x25 = x16 + x2*uq3;
        const double x26 = x5*uq2;
        const double x27 = x5*uq1;
        const double x28 = x3*uq0;
        const double x29 = x5*x22*mu0/(x3*mu2);
        const double x30 = x18*(x10 - x13 + 2*x15);

        f[0] = uq1 + v0*uq4;
        f[1] = x19 + x8 + v0*uq5 + x0*x2;
        f[2] = x24 + v0*uq6;
        f[3] = uq1*x25 + v0*uq7 + x11*x19 + x29*(x28*(uq7 - x6*uq4 - (x20*x26 + x27*x12)*uq0) - x8*uq4) + x9*x23;
        f[4] = uq2 + v0*uq8;
        f[5] = x24 + v0*uq9;
        f[6] = x30 + x8 + v0*uq10 + x2*x4;
        f[7] = uq2*x25 + v0*uq11 + x23*x11 + x29*(x28*(uq11 - x6*uq8 - (x21*x27 + x26*x14)*uq0) - x8*uq8) + x9*x30;
    }

    KOKKOS_INLINE_FUNCTION static
    void source(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double x1 = x[1];
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];
        const double uq4 = uq[4];
        const double uq5 = uq[5];
        const double uq6 = uq[6];
        const double uq8 = uq[8];
        const double uq9 = uq[9];
        const double uq10 = uq[10];
        const double uq11 = uq[11];
        const double v0 = v[0];
        const double mu0 = mu[0];
        const double mu1 = mu[1];
        const double mu2 = mu[2];
        const double mu3 = mu[3];
        const double mu9 = mu[9];

        const double x0 = pow(x1, -1);
        const double x2 = pow(uq0, -1);
        const double x3 = x2*uq2;
        const double x4 = x2*uq1;
        const double x5 = uq9 - x4*uq8;
        const double x6 = -1.0 + mu0;
        const double x7 = pow(uq2, 2);
        const double x8 = pow(uq0, -2);
        const double x9 = 0.5*(x8*pow(uq1, 2) + x8*x7);
        const double x10 = uq3 - x9*uq0;
        const double x11 = x6*x10;
        const double x12 = x2*x11;
        const double x13 = sqrt(pow(x6, 3)*pow(x10, 3)*pow(mu3, 6)*pow(mu0, 3)/pow(uq0, 3))*(110.4 + mu9)/(mu1*(110.4 + 1.0*x12*pow(mu3, 2)*mu9*mu0));
        const double x14 = 1.0*x13;
        const double x15 = uq10 - x3*uq8;
        const double x16 = x2*x15;
        const double x17 = x0*x3;
        const double x18 = -x2*(uq5 - x4*uq4);
        const double x19 = 0.666666666666667*x13;
        const double x20 = x19*(2*x16 + x17 + x18);

        f[0] = -x0*(uq2 + v0*uq8);
        f[1] = -x0*(v0*uq9 + x14*(x2*x5 + x2*(uq6 - x3*uq4)) + x4*uq2);
        f[2] = -x0*(x20 + v0*uq10 - x19*(-x16 - 2*x17 + x18) + x2*x7);
        f[3] = -x0*(uq2*(x12 + x2*uq3) + v0*uq11 + x3*x20 + x8*x14*mu0*(-uq8*x11 + x6*uq0*(uq11 - uq0*(x5*x8*uq1 + x8*uq2*x15) - x9*uq8))/(x6*mu2));
    }

    KOKKOS_INLINE_FUNCTION static
    void tdfunc(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {

        f[0] = 1;
        f[1] = 1;
        f[2] = 1;
        f[3] = 1;
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_scalars(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];

        const double x0 = pow(uq0, -1);

        f[0] = uq0;
        f[1] = x0*uq1;
        f[2] = x0*uq2;
        f[3] = 0.4*(uq3 - 0.5*(x0*pow(uq1, 2) + x0*pow(uq2, 2)));
    }

    KOKKOS_INLINE_FUNCTION static
    void vis_vectors(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double uq1 = uq[1];
        const double uq2 = uq[2];

        f[0] = uq1;
        f[1] = uq2;
    }

    KOKKOS_INLINE_FUNCTION static
    void initu(double f[], const double x[], const double uinf[], const double mu[]) {
        const double mu4 = mu[4];
        const double mu5 = mu[5];
        const double mu6 = mu[6];
        const double mu7 = mu[7];

        f[0] = mu4;
        f[1] = mu5;
        f[2] = mu6;
        f[3] = mu7;
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou(double f[], int ib, const double x[], const double uq[], const double v[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void ubou(double f[], int ib, const double x[], const double uq[], const double v[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
        else if (ib == 2) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg(double f[], int ib, const double x[], const double uq[], const double v[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {
            const double uhat0 = uh[0];
            const double uhat1 = uh[1];
            const double uhat2 = uh[2];
            const double uhat3 = uh[3];
            const double mu4 = mu[4];
            const double mu5 = mu[5];
            const double mu6 = mu[6];
            const double mu7 = mu[7];

            f[0] = mu4 - uhat0;
            f[1] = mu5 - uhat1;
            f[2] = mu6 - uhat2;
            f[3] = mu7 - uhat3;
        }
        else if (ib == 2) {
            const double uq0 = uq[0];
            const double uq1 = uq[1];
            const double uq2 = uq[2];
            const double uq3 = uq[3];
            const double uhat0 = uh[0];
            const double uhat1 = uh[1];
            const double uhat2 = uh[2];
            const double uhat3 = uh[3];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1 + uq1;
            f[2] = -uhat2 + uq2;
            f[3] = -uhat3 + uq3;
        }
        else if (ib == 3) {
            const double uq0 = uq[0];
            const double uhat0 = uh[0];
            const double uhat1 = uh[1];
            const double uhat2 = uh[2];
            const double uhat3 = uh[3];
            const double mu8 = mu[8];
            const double mu9 = mu[9];
            const double mu10 = mu[10];

            f[0] = -uhat0 + uq0;
            f[1] = -uhat1;
            f[2] = -uhat2;
            f[3] = -uhat3 + mu8*mu10*uhat0/mu9;
        }
        else if (ib == 4) {
            const double uq0 = uq[0];
            const double uq1 = uq[1];
            const double uq2 = uq[2];
            const double uq3 = uq[3];
            const double uq4 = uq[4];
            const double uq5 = uq[5];
            const double uq6 = uq[6];
            const double uq7 = uq[7];
            const double uq8 = uq[8];
            const double uq9 = uq[9];
            const double uq10 = uq[10];
            const double uq11 = uq[11];
            const double uhat0 = uh[0];
            const double uhat1 = uh[1];
            const double uhat2 = uh[2];
            const double uhat3 = uh[3];
            const double n0 = n[0];
            const double n1 = n[1];
            const double tau0 = tau[0];

            f[0] = n0*uq4 + n1*uq8 + tau0*(-uhat0 + uq0);
            f[1] = n0*uq5 + n1*uq9 + tau0*(-uhat1 + uq1);
            f[2] = n0*uq6 + n1*uq10 + tau0*(-uhat2 + uq2);
            f[3] = n0*uq7 + n1*uq11 + tau0*(-uhat3 + uq3);
        }
        else if (ib == 5) {
            const double uq0 = uq[0];
            const double uq1 = uq[1];
            const double uq2 = uq[2];
            const double uq3 = uq[3];
            const double uhat0 = uh[0];
            const double uhat1 = uh[1];
            const double uhat2 = uh[2];
            const double uhat3 = uh[3];
            const double n0 = n[0];
            const double n1 = n[1];
            const double tau0 = tau[0];

            const double x0 = n0*uq1 + n1*uq2;

            f[0] = tau0*(-uhat0 + uq0);
            f[1] = tau0*(-uhat1 + uq1 - n0*x0);
            f[2] = tau0*(-uhat2 + uq2 - n1*x0);
            f[3] = tau0*(-uhat3 + uq3);
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void flux_jac_uq(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double x1 = x[1];
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];
        const double uq4 = uq[4];
        const double uq5 = uq[5];
        const double uq6 = uq[6];
        const double uq7 = uq[7];
        const double uq8 = uq[8];
        const double uq9 = uq[9];
        const double uq10 = uq[10];
        const double uq11 = uq[11];
        const double v0 = v[0];
        const double mu0 = mu[0];
        const double mu1 = mu[1];
        const double mu2 = mu[2];
        const double mu3 = mu[3];
        const double mu9 = mu[9];

        const double x0 = pow(x1, -1);
        const double x2 = pow(uq0, -1);
        const double x3 = x0*x2;
        const double x4 = x3*uq2;
        const double x5 = x2*uq1;
        const double x6 = uq5 - x5*uq4;
        const double x7 = x2*x6;
        const double x8 = x2*uq2;
        const double x9 = uq10 - x8*uq8;
        const double x10 = x2*x9;
        const double x11 = -x10 + x4 + 2*x7;
        const double x12 = pow(uq1, 2);
        const double x13 = pow(uq0, -3);
        const double x14 = x13*x12;
        const double x15 = pow(uq2, 2);
        const double x16 = x15*x13;
        const double x17 = 0.5*(-2*x14 - 2*x16);
        const double x18 = pow(uq0, -2);
        const double x19 = x15*x18;
        const double x20 = x12*x18;
        const double x21 = -0.5*x19 - 0.5*x20;
        const double x22 = x21 - uq0*x17;
        const double x23 = 0.5*(x19 + x20);
        const double x24 = uq3 - uq0*x23;
        const double x25 = pow(x24, 2);
        const double x26 = pow(mu3, 6);
        const double x27 = -1.0 + mu0;
        const double x28 = x26*pow(x27, 3)*pow(mu0, 3);
        const double x29 = x25*x28;
        const double x30 = x29*x13;
        const double x31 = pow(uq0, -4);
        const double x32 = pow(x24, 3)*x28;
        const double x33 = sqrt(x32*x13);
        const double x34 = pow(mu1, -1);
        const double x35 = 110.4 + mu9;
        const double x36 = x2*x27;
        const double x37 = x36*x24;
        const double x38 = 1.0*mu0;
        const double x39 = pow(mu3, 2)*mu9;
        const double x40 = x38*x39;
        const double x41 = 110.4 + x40*x37;
        const double x42 = x34*x35/x41;
        const double x43 = x42/x33;
        const double x44 = (3*x30*x22 - 3*x32*x31)*x43;
        const double x45 = 0.333333333333333*x44;
        const double x46 = x45*x11;
        const double x47 = x24*x27;
        const double x48 = x47*x18;
        const double x49 = x36*x22;
        const double x50 = x34*x33*x35/pow(x41, 2);
        const double x51 = (-x40*x48 + x40*x49)*x50;
        const double x52 = 0.666666666666667*x51;
        const double x53 = x52*x11;
        const double x54 = uq2*x18;
        const double x55 = -x0*x54;
        const double x56 = x6*x18;
        const double x57 = uq4*x13;
        const double x58 = uq1*x57;
        const double x59 = x9*x18;
        const double x60 = uq8*x13;
        const double x61 = uq2*x60;
        const double x62 = x59 - x61;
        const double x63 = x42*x33;
        const double x64 = 0.666666666666667*x63;
        const double x65 = (x55 - 2*x56 + 2*x58 + x62)*x64;
        const double x66 = x22*x27;
        const double x67 = uq6 - x8*uq4;
        const double x68 = uq9 - x5*uq8;
        const double x69 = x2*x67 + x2*x68;
        const double x70 = 0.5*x44;
        const double x71 = x70*x69;
        const double x72 = x68*x18;
        const double x73 = uq1*x60;
        const double x74 = x67*x18;
        const double x75 = uq2*x57;
        const double x76 = 1.0*x63;
        const double x77 = (-x72 + x73 - x74 + x75)*x76;
        const double x78 = uq1*x54;
        const double x79 = 1.0*x69*x51;
        const double x80 = x71 + x77 - x78 - x79;
        const double x81 = uq2*x74;
        const double x82 = uq1*x56;
        const double x83 = x27*(uq7 - uq4*x23 - (x81 + x82)*uq0);
        const double x84 = uq0*x83 - uq4*x47;
        const double x85 = pow(x27, -1);
        const double x86 = pow(mu2, -1);
        const double x87 = x86*mu0;
        const double x88 = x85*x87;
        const double x89 = x88*x84;
        const double x90 = x70*x18;
        const double x91 = x85*x51*x38*x18;
        const double x92 = x84*x86;
        const double x93 = uq1*x18;
        const double x94 = x64*x93;
        const double x95 = -x48 + x49 - uq3*x18;
        const double x96 = x76*x54;
        const double x97 = 2*x13;
        const double x98 = uq1*x97;
        const double x99 = uq2*x97;
        const double x100 = x31*x12;
        const double x101 = x31*x15;
        const double x102 = uq0*x27;
        const double x103 = x88*x76*x18;
        const double x104 = x63*x13;
        const double x105 = 2.0*x104;
        const double x106 = 2*x10 + x4 - x7;
        const double x107 = x45*x106;
        const double x108 = x52*x106;
        const double x109 = x56 - x58;
        const double x110 = x64*(x109 + x55 - 2*x59 + 2*x61);
        const double x111 = uq2*x59;
        const double x112 = uq1*x72;
        const double x113 = x27*(uq11 - uq8*x23 - (x111 + x112)*uq0);
        const double x114 = uq0*x113 - uq8*x47;
        const double x115 = x88*x114;
        const double x116 = x64*x54;
        const double x117 = x86*x114;
        const double x118 = x76*x93;
        const double x119 = x43*x29;
        const double x120 = 1.0*x119;
        const double x121 = x11*x120;
        const double x122 = uq1*x31;
        const double x123 = x122*x121;
        const double x124 = x50*x39;
        const double x125 = mu0*x124;
        const double x126 = 0.666666666666667*x125;
        const double x127 = x27*x126;
        const double x128 = x11*x127;
        const double x129 = x93*x128;
        const double x130 = 1.33333333333333*x63;
        const double x131 = uq4*x18;
        const double x132 = 1.0*x36;
        const double x133 = uq1*x132;
        const double x134 = -x133;
        const double x135 = 1.5*x69;
        const double x136 = x119*x135;
        const double x137 = x122*x136;
        const double x138 = uq8*x18;
        const double x139 = 1.0*x138;
        const double x140 = x63*x139;
        const double x141 = 1.0*x27;
        const double x142 = x69*x125;
        const double x143 = x142*x141;
        const double x144 = x93*x143;
        const double x145 = -x137 - x140 + x144 + x8;
        const double x146 = 1.5*x43*x25*x26*pow(x27, 2)*pow(mu0, 4);
        const double x147 = x146/pow(uq0, 6);
        const double x148 = x92*x147;
        const double x149 = 1.0*uq4;
        const double x150 = 1.0*pow(mu0, 2)*x124;
        const double x151 = x92*x150;
        const double x152 = x2*x64;
        const double x153 = pow(uq0, -5);
        const double x154 = x12*x153;
        const double x155 = uq2*uq1;
        const double x156 = x13*x155;
        const double x157 = x153*x155;
        const double x158 = x37 - x136*x157 + x143*x156 + x2*uq3;
        const double x159 = x106*x120;
        const double x160 = x106*x127;
        const double x161 = x117*x147;
        const double x162 = x117*x150;
        const double x163 = x2*x76;
        const double x164 = x69*x163 - x78*x141;
        const double x165 = uq2*x31;
        const double x166 = x64*(x138 + x3);
        const double x167 = x54*x127;
        const double x168 = uq2*x132;
        const double x169 = -x168;
        const double x170 = x165*x136;
        const double x171 = x54*x143;
        const double x172 = x63*x18*x149;
        const double x173 = -x170 + x171 - x172 + x5;
        const double x174 = x15*x153;
        const double x175 = x165*x159;
        const double x176 = x64*(-2*x138 + x3);
        const double x177 = x106*x167;
        const double x178 = x36*x126;
        const double x179 = x43*x30;
        const double x180 = 1.0*x179;
        const double x181 = -x132*x142 + x179*x135;
        const double x182 = x146*x153;
        const double x183 = x13*x150;
        const double x184 = x2 + x36;
        const double x185 = x93*x130;
        const double x186 = -x96;
        const double x187 = x103*(-x47 + x102*(x21 - (-x14 - x16)*uq0));
        const double x188 = -0.333333333333333*x104*x155;
        const double x189 = v0 + x2*x130;
        const double x190 = -x87*x118;
        const double x191 = -x152;
        const double x192 = v0 + x163;
        const double x193 = -x87*x96;
        const double x194 = v0 + x87*x163;
        const double x195 = -x118;
        const double x196 = x54*x130;

        f[0] = 0;
        f[1] = -x20 + x46 - x53 + x65 + x66;
        f[2] = x80;
        f[3] = uq1*x95 + x103*(x83 - uq4*x66 + x102*(-x81 - x82 - uq0*(uq4*x100 + uq4*x101 - x6*x98 - x67*x99) - uq4*x17)) + x5*x46 - x5*x53 + x5*x65 - x69*x96 + x8*x71 + x8*x77 - x8*x79 - x89*x105 + x89*x90 - x92*x91 - x94*x11;
        f[4] = 0;
        f[5] = x80;
        f[6] = x107 - x108 + x110 - x19 + x66;
        f[7] = uq2*x95 + x103*(x113 - uq8*x66 + x102*(-x111 - x112 - uq0*(uq8*x100 + uq8*x101 - x68*x98 - x9*x99) - uq8*x17)) - x105*x115 - x106*x116 + x5*x71 + x5*x77 - x5*x79 - x69*x118 + x8*x107 - x8*x108 + x8*x110 + x90*x115 - x91*x117;
        f[8] = 1;
        f[9] = -x123 + x129 + x134 + 2*x5 - x130*x131;
        f[10] = x145;
        f[11] = x158 - uq1*x148 + x103*(uq4*x133 + (-uq0*x109 - x93*x149)*x102) + x11*x152 - x121*x154 + x122*x151 + x14*x128 - x20*x141 - x58*x130 - x76*x61;
        f[12] = 0;
        f[13] = x145;
        f[14] = x134 - x122*x159 + x64*x131 + x93*x160;
        f[15] = x164 - uq1*x161 + x103*(uq8*x133 + x102*(-uq1*x139 - (x72 - x73)*uq0)) + x122*x162 - x136*x154 + x14*x143 - x157*x159 + x160*x156 - x73*x76 + x75*x64;
        f[16] = 0;
        f[17] = x166 + x169 + x11*x167 - x121*x165;
        f[18] = x173;
        f[19] = x164 - uq2*x148 + x103*(uq4*x168 + x102*(-x54*x149 - (x74 - x75)*uq0)) - x121*x157 + x128*x156 + x16*x143 + x165*x151 - x174*x136 + x5*x166 - x75*x76;
        f[20] = 1;
        f[21] = x173;
        f[22] = x169 - x175 + x176 + x177 + 2*x8;
        f[23] = x158 - uq2*x161 + x103*(uq8*x168 + x102*(-uq0*x62 - uq2*x139)) + x106*x152 + x16*x160 + x165*x162 - x174*x159 - x19*x141 - x76*x58 + x8*x176;
        f[24] = 0;
        f[25] = x27 - x11*x178 + x11*x180;
        f[26] = x181;
        f[27] = x123 - x129 + x170 - x171 + uq1*x184 - x87*x172 + x92*x182 - x92*x183;
        f[28] = 0;
        f[29] = x181;
        f[30] = x27 - x106*x178 + x106*x180;
        f[31] = x137 - x144 + x175 - x177 + uq2*x184 + x117*x182 - x117*x183 - x87*x140;
        f[32] = v0;
        f[33] = -x185;
        f[34] = x186;
        f[35] = x187 - x14*x130 - x76*x16;
        f[36] = 0;
        f[37] = x186;
        f[38] = x94;
        f[39] = x188;
        f[40] = 0;
        f[41] = x189;
        f[42] = 0;
        f[43] = x185 + x190;
        f[44] = 0;
        f[45] = 0;
        f[46] = x191;
        f[47] = -x116;
        f[48] = 0;
        f[49] = 0;
        f[50] = x192;
        f[51] = x193 + x96;
        f[52] = 0;
        f[53] = x163;
        f[54] = 0;
        f[55] = x118;
        f[56] = 0;
        f[57] = 0;
        f[58] = 0;
        f[59] = x194;
        f[60] = 0;
        f[61] = 0;
        f[62] = 0;
        f[63] = 0;
        f[64] = 0;
        f[65] = x116;
        f[66] = x195;
        f[67] = x188;
        f[68] = v0;
        f[69] = x195;
        f[70] = -x196;
        f[71] = x187 - x16*x130 - x76*x14;
        f[72] = 0;
        f[73] = 0;
        f[74] = x163;
        f[75] = x96;
        f[76] = 0;
        f[77] = x192;
        f[78] = 0;
        f[79] = x118 + x190;
        f[80] = 0;
        f[81] = x191;
        f[82] = 0;
        f[83] = -x94;
        f[84] = 0;
        f[85] = 0;
        f[86] = x189;
        f[87] = x193 + x196;
        f[88] = 0;
        f[89] = 0;
        f[90] = 0;
        f[91] = 0;
        f[92] = 0;
        f[93] = 0;
        f[94] = 0;
        f[95] = x194;
    }

    KOKKOS_INLINE_FUNCTION static
    void source_jac_uq(double f[], const double x[], const double uq[], const double v[], const double w[], const double mu[], const double uinf[], double t) {
        const double x1 = x[1];
        const double uq0 = uq[0];
        const double uq1 = uq[1];
        const double uq2 = uq[2];
        const double uq3 = uq[3];
        const double uq4 = uq[4];
        const double uq5 = uq[5];
        const double uq6 = uq[6];
        const double uq8 = uq[8];
        const double uq9 = uq[9];
        const double uq10 = uq[10];
        const double uq11 = uq[11];
        const double v0 = v[0];
        const double mu0 = mu[0];
        const double mu1 = mu[1];
        const double mu2 = mu[2];
        const double mu3 = mu[3];
        const double mu9 = mu[9];

        const double x0 = pow(x1, -1);
        const double x2 = pow(uq0, -1);
        const double x3 = x2*uq2;
        const double x4 = uq6 - x3*uq4;
        const double x5 = x2*uq1;
        const double x6 = uq9 - x5*uq8;
        const double x7 = x2*x4 + x2*x6;
        const double x8 = pow(uq1, 2);
        const double x9 = pow(uq0, -3);
        const double x10 = x8*x9;
        const double x11 = pow(uq2, 2);
        const double x12 = x9*x11;
        const double x13 = 0.5*(-2*x10 - 2*x12);
        const double x14 = pow(uq0, -2);
        const double x15 = x14*x11;
        const double x16 = x8*x14;
        const double x17 = -0.5*x15 - 0.5*x16;
        const double x18 = x17 - uq0*x13;
        const double x19 = 0.5*(x15 + x16);
        const double x20 = uq3 - uq0*x19;
        const double x21 = pow(x20, 2);
        const double x22 = pow(mu3, 6);
        const double x23 = -1.0 + mu0;
        const double x24 = x22*pow(x23, 3)*pow(mu0, 3);
        const double x25 = x24*x21;
        const double x26 = x9*x25;
        const double x27 = pow(uq0, -4);
        const double x28 = x24*pow(x20, 3);
        const double x29 = sqrt(x9*x28);
        const double x30 = pow(mu1, -1);
        const double x31 = 110.4 + mu9;
        const double x32 = x2*x23;
        const double x33 = x32*x20;
        const double x34 = 1.0*mu0;
        const double x35 = pow(mu3, 2)*mu9;
        const double x36 = x34*x35;
        const double x37 = 110.4 + x33*x36;
        const double x38 = x30*x31/x37;
        const double x39 = x38/x29;
        const double x40 = (3*x26*x18 - 3*x28*x27)*x39;
        const double x41 = 0.5*x40;
        const double x42 = x6*x14;
        const double x43 = x9*uq8;
        const double x44 = uq1*x43;
        const double x45 = x9*uq4;
        const double x46 = uq2*x45;
        const double x47 = x38*x29;
        const double x48 = 1.0*x47;
        const double x49 = uq2*x14;
        const double x50 = uq1*x49;
        const double x51 = x23*x20;
        const double x52 = x51*x14;
        const double x53 = x32*x18;
        const double x54 = x30*x31*x29/pow(x37, 2);
        const double x55 = (-x52*x36 + x53*x36)*x54;
        const double x56 = x0*x2;
        const double x57 = uq10 - x3*uq8;
        const double x58 = x2*x57;
        const double x59 = uq5 - x5*uq4;
        const double x60 = -x2*x59;
        const double x61 = 2*x58 + x60 + uq2*x56;
        const double x62 = 0.333333333333333*x40;
        const double x63 = x61*x62;
        const double x64 = uq2*x43;
        const double x65 = x57*x14;
        const double x66 = x0*x49;
        const double x67 = -uq1*x45 + x59*x14;
        const double x68 = 0.666666666666667*x47;
        const double x69 = (2*x64 - 2*x65 - x66 + x67)*x68;
        const double x70 = 2*x56;
        const double x71 = -x58 + x60 - uq2*x70;
        const double x72 = 0.666666666666667*x55;
        const double x73 = x72*x61;
        const double x74 = -x64 + x65;
        const double x75 = pow(x23, -1);
        const double x76 = pow(mu2, -1);
        const double x77 = x76*mu0;
        const double x78 = x75*x77;
        const double x79 = uq2*x65;
        const double x80 = uq1*x42;
        const double x81 = x23*(uq11 - uq8*x19 - (x79 + x80)*uq0);
        const double x82 = uq0*x81 - uq8*x51;
        const double x83 = x82*x14;
        const double x84 = 2*x9;
        const double x85 = uq8*x27;
        const double x86 = uq0*x23;
        const double x87 = x48*x14;
        const double x88 = x87*x78;
        const double x89 = 2.0*x47;
        const double x90 = x9*x82;
        const double x91 = x61*x68;
        const double x92 = uq1*x27;
        const double x93 = 1.5*x7;
        const double x94 = x39*x25;
        const double x95 = x93*x94;
        const double x96 = uq8*x14;
        const double x97 = 1.0*x96;
        const double x98 = x97*x47;
        const double x99 = 1.0*x23;
        const double x100 = x54*x35;
        const double x101 = mu0*x100;
        const double x102 = x7*x101;
        const double x103 = x99*x102;
        const double x104 = uq1*x14;
        const double x105 = 1.0*x94;
        const double x106 = x92*x105;
        const double x107 = 0.666666666666667*x101;
        const double x108 = x23*x107;
        const double x109 = x61*x108;
        const double x110 = x71*x108;
        const double x111 = 1.0*x32;
        const double x112 = uq8*x111;
        const double x113 = 1.5*x82*x76*x39*x22*pow(x23, 2)*x21*pow(mu0, 4);
        const double x114 = x113/pow(uq0, 6);
        const double x115 = 1.0*x76*pow(mu0, 2)*x100;
        const double x116 = x82*x115;
        const double x117 = pow(uq0, -5);
        const double x118 = x61*x105*x117;
        const double x119 = x9*uq2;
        const double x120 = uq2*x27;
        const double x121 = x105*x120;
        const double x122 = x61*x121;
        const double x123 = x49*x109;
        const double x124 = (x56 - 2*x96)*x68;
        const double x125 = x39*x26;
        const double x126 = 1.0*x125;
        const double x127 = x32*x107;
        const double x128 = x0*uq1;
        const double x129 = x87*x128;
        const double x130 = 1.33333333333333*x47;
        const double x131 = x2*x48;

        f[0] = 0;
        f[1] = -x0*(-x50 + x48*(-x42 + x44 + x46 - x4*x14) + x7*x41 - 1.0*x7*x55);
        f[2] = -x0*(-x15 + x63 + x69 - x73 - x68*(2*x66 + x67 + x74) - x71*x62 + x71*x72);
        f[3] = -x0*(uq2*(-x52 + x53 - uq3*x14) + x3*x63 + x3*x69 - x3*x73 + x88*(x81 + x86*(-x79 - x80 - uq0*(x8*x85 + x85*x11 - uq2*x84*x57 - x6*uq1*x84) - uq8*x13) - uq8*x23*x18) - x91*x49 + x83*x78*x41 - x89*x78*x90 - x83*x75*x76*x55*x34);
        f[4] = 0;
        f[5] = -x0*(x3 - x98 + x103*x104 - x92*x95);
        f[6] = -x0*(-x104*x110 + x109*x104 - x61*x106 + x71*x106);
        f[7] = -x0*(-uq1*x114 - x50*x99 + x68*x46 + x88*(uq1*x112 + x86*(-uq1*x97 - (x42 - x44)*uq0)) + x92*x116 + uq1*x109*x119 - uq2*uq1*x118);
        f[8] = -x0;
        f[9] = -x0*(x5 - uq4*x87 + x49*x103 - x95*x120);
        f[10] = -x0*(-x122 + x123 + x124 + 2*x3 - x49*x110 + x71*x121 - (-x70 + x96)*x68);
        f[11] = -x0*(x33 - uq2*x114 - x11*x118 + x116*x120 + x12*x109 + x2*uq3 + x2*x91 + x3*x124 + x88*(uq2*x112 + (-uq0*x74 - uq2*x97)*x86) - x99*x15);
        f[12] = 0;
        f[13] = -x0*(-x102*x111 + x93*x125);
        f[14] = -(x61*x126 - x61*x127 - x71*x126 + x71*x127)*x0;
        f[15] = -x0*(x122 - x123 + uq2*(x2 + x32) + x113*x117 - x77*x98 - x90*x115);
        f[16] = 0;
        f[17] = x66*x48;
        f[18] = 0;
        f[19] = -x68*x119*x128;
        f[20] = 0;
        f[21] = 0;
        f[22] = 0;
        f[23] = x68*x66;
        f[24] = 0;
        f[25] = -x56*x48;
        f[26] = 0;
        f[27] = 0;
        f[28] = 0;
        f[29] = 0;
        f[30] = 0;
        f[31] = 0;
        f[32] = -v0*x0;
        f[33] = x129;
        f[34] = x89*x66;
        f[35] = -x0*(-x12*x130 + x88*(-x51 + x86*(x17 - (-x10 - x12)*uq0)));
        f[36] = 0;
        f[37] = -x0*(v0 + x131);
        f[38] = 0;
        f[39] = x77*x129;
        f[40] = 0;
        f[41] = 0;
        f[42] = -x0*(v0 + x2*x89);
        f[43] = -x0*(x49*x130 - x77*x48*x49);
        f[44] = 0;
        f[45] = 0;
        f[46] = 0;
        f[47] = -x0*(v0 + x77*x131);
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uq(double f[], int ib, const double x[], const double uq[], const double v[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = 0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 2) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 1;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 3) {

            f[0] = 1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = 0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = 0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = 0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
        else if (ib == 4) {
            const double n0 = n[0];
            const double n1 = n[1];
            const double tau0 = tau[0];

            f[0] = tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = tau0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = tau0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = tau0;
            f[16] = n0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = n0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = n0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = n0;
            f[32] = n1;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = n1;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = n1;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = n1;
        }
        else if (ib == 5) {
            const double n0 = n[0];
            const double n1 = n[1];
            const double tau0 = tau[0];

            const double x0 = -n1*n0*tau0;

            f[0] = tau0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = tau0*(1 - pow(n0, 2));
            f[6] = x0;
            f[7] = 0;
            f[8] = 0;
            f[9] = x0;
            f[10] = tau0*(1 - pow(n1, 2));
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = tau0;
            f[16] = 0;
            f[17] = 0;
            f[18] = 0;
            f[19] = 0;
            f[20] = 0;
            f[21] = 0;
            f[22] = 0;
            f[23] = 0;
            f[24] = 0;
            f[25] = 0;
            f[26] = 0;
            f[27] = 0;
            f[28] = 0;
            f[29] = 0;
            f[30] = 0;
            f[31] = 0;
            f[32] = 0;
            f[33] = 0;
            f[34] = 0;
            f[35] = 0;
            f[36] = 0;
            f[37] = 0;
            f[38] = 0;
            f[39] = 0;
            f[40] = 0;
            f[41] = 0;
            f[42] = 0;
            f[43] = 0;
            f[44] = 0;
            f[45] = 0;
            f[46] = 0;
            f[47] = 0;
        }
    }

    KOKKOS_INLINE_FUNCTION static
    void fbou_hdg_jac_uh(double f[], int ib, const double x[], const double uq[], const double v[], const double w[], const double uh[], const double n[], const double tau[], const double mu[], const double uinf[], double t) {
        if (ib == 1) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 2) {

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 3) {
            const double mu8 = mu[8];
            const double mu9 = mu[9];
            const double mu10 = mu[10];

            f[0] = -1;
            f[1] = 0;
            f[2] = 0;
            f[3] = mu8*mu10/mu9;
            f[4] = 0;
            f[5] = -1;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = -1;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = -1;
        }
        else if (ib == 4) {
            const double tau0 = tau[0];

            const double x0 = -tau0;

            f[0] = x0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = x0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = x0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = x0;
        }
        else if (ib == 5) {
            const double tau0 = tau[0];

            const double x0 = -tau0;

            f[0] = x0;
            f[1] = 0;
            f[2] = 0;
            f[3] = 0;
            f[4] = 0;
            f[5] = x0;
            f[6] = 0;
            f[7] = 0;
            f[8] = 0;
            f[9] = 0;
            f[10] = x0;
            f[11] = 0;
            f[12] = 0;
            f[13] = 0;
            f[14] = 0;
            f[15] = x0;
        }
    }

};
