// SPDX-License-Identifier: see LICENSE
//
// <exasim/kernels/flux.hpp> — templated flux kernels.
//
// Replaces the role played today by `KokkosFlux` and `HdgFlux` in
// `backend/Model/libpdemodel.hpp`. Each generated `Kokkos*1.cpp`
// produced by text2code becomes a single `Kokkos::parallel_for` over
// quadrature points that gathers SoA inputs into a pointwise array,
// calls the model's pointwise function, and scatters the result back.
//
// The kernel templates here do exactly that, but with the model
// supplied as a template parameter `M` rather than a global extern
// symbol. The Kokkos lambda body inlines `M::flux(...)` (and, for
// HDG, `M::flux_jac_uq(...)`) at compile time.
//
// Storage layout & Jacobian indexing conventions: see <exasim/model.hpp>.

#pragma once

#include <Kokkos_Core.hpp>

#include "../common.h"
#include "../model.hpp"

namespace exasim {

// LDG / forward path: compute f only.
//
// Signature mirrors `KokkosFlux` from libpdemodel.hpp so call sites
// can swap by changing only the function name:
//   KokkosFlux(f, xdg, udg, odg, wdg, uinf, param, t, model, ng, nc,
//              ncu, nd, ncx, nco, ncw);
// becomes
//   exasim::flux_kernel<MyModel>(f, xdg, udg, odg, wdg, uinf, param,
//                                t, model, ng, nc, ncu, nd, ncx, nco, ncw);
//
// The runtime `ncu/nd/ncw/nc/ncx/nco` arguments are accepted for ABI
// compatibility but are *not* read — the kernel uses `M::ncu` /
// `M::nd` / `M::ncw` (compile-time constants) instead. A debug-only
// assert verifies they agree.
template <class M>
void flux_kernel(dstype*       f,
                 const dstype* xdg,
                 const dstype* udg,
                 const dstype* odg,
                 const dstype* wdg,
                 const dstype* /*uinf*/,
                 const dstype* param,
                 dstype        t,
                 int           /*modelnumber*/,
                 int           ng,
                 int           /*nc*/,
                 int           ncu_runtime,
                 int           nd_runtime,
                 int           /*ncx*/,
                 int           /*nco*/,
                 int           ncw_runtime)
{
    static_assert(is_model_v<M>,
                  "flux_kernel<M>: M must satisfy the Model contract — "
                  "see <exasim/model.hpp>.");

    constexpr int nd  = M::nd;
    constexpr int ncu = M::ncu;
    constexpr int ncw = M::ncw;
    constexpr int nco = M::nco;
    constexpr int Nq  = ncu * (1 + nd);

    assert(ncu_runtime == ncu && nd_runtime == nd && ncw_runtime == ncw &&
           "flux_kernel<M>: runtime ncu/nd/ncw disagree with M's compile-time "
           "constants. The model and the dataset disagree about dimensions.");
    (void)ncu_runtime; (void)nd_runtime; (void)ncw_runtime;

    // C++ requires array sizes to be > 0; clamp unused-when-zero local
    // buffers to 1 element to keep the lambda body well-formed.
    constexpr int ncw_buf = (ncw > 0) ? ncw : 1;
    constexpr int nco_buf = (nco > 0) ? nco : 1;

    Kokkos::parallel_for("exasim::flux_kernel", ng,
        KOKKOS_LAMBDA(const size_t i) {
            double x [nd];
            double uq[Nq];
            double v [nco_buf];
            double w [ncw_buf];

            for (int k = 0; k < nd;  ++k) x [k] = xdg[k * ng + i];
            for (int k = 0; k < Nq;  ++k) uq[k] = udg[k * ng + i];
            if constexpr (nco > 0) {
                for (int k = 0; k < nco; ++k) v[k] = odg[k * ng + i];
            }
            if constexpr (ncw > 0) {
                for (int k = 0; k < ncw; ++k) w[k] = wdg[k * ng + i];
            }

            double f_local[ncu * nd];
            M::flux(f_local, x, uq, v, w, param, /*uinf=*/nullptr, t);

            for (int k = 0; k < ncu * nd; ++k) f[k * ng + i] = f_local[k];
        });
}

// HDG path: compute f, f_udg = ∂f/∂uq, and (when ncw > 0) f_wdg = ∂f/∂w.
//
// Replaces `HdgFlux` from libpdemodel.hpp. The user's hand-written
// pointwise Jacobian methods (`M::flux_jac_uq`, `M::flux_jac_w`)
// supply the derivatives — no autodiff.
//
// Layouts (consistent with the kernel-side code generated by
// text2code today):
//   f    [k * ng + i]                       k in [0, ncu*nd)
//   f_udg[k * ng + i]                       k in [0, ncu*nd*Nq)
//                                           index = (out * Nq) + j
//   f_wdg[k * ng + i]                       k in [0, ncu*nd*ncw)
//                                           index = (out * ncw) + j
template <class M>
void hdg_flux_kernel(dstype*       f,
                     dstype*       f_udg,
                     dstype*       f_wdg,
                     const dstype* xdg,
                     const dstype* udg,
                     const dstype* odg,
                     const dstype* wdg,
                     const dstype* /*uinf*/,
                     const dstype* param,
                     dstype        t,
                     int           /*modelnumber*/,
                     int           ng,
                     int           /*nc*/,
                     int           ncu_runtime,
                     int           nd_runtime,
                     int           /*ncx*/,
                     int           /*nco*/,
                     int           ncw_runtime)
{
    static_assert(is_model_v<M>,
                  "hdg_flux_kernel<M>: M must satisfy the Model contract.");

    constexpr int nd  = M::nd;
    constexpr int ncu = M::ncu;
    constexpr int ncw = M::ncw;
    constexpr int nco = M::nco;
    constexpr int Nq  = ncu * (1 + nd);

    assert(ncu_runtime == ncu && nd_runtime == nd && ncw_runtime == ncw);
    (void)ncu_runtime; (void)nd_runtime; (void)ncw_runtime;

    constexpr int ncw_buf = (ncw > 0) ? ncw : 1;
    constexpr int nco_buf = (nco > 0) ? nco : 1;

    Kokkos::parallel_for("exasim::hdg_flux_kernel", ng,
        KOKKOS_LAMBDA(const size_t i) {
            double x [nd];
            double uq[Nq];
            double v [nco_buf];
            double w [ncw_buf];

            for (int k = 0; k < nd; ++k) x [k] = xdg[k * ng + i];
            for (int k = 0; k < Nq; ++k) uq[k] = udg[k * ng + i];
            if constexpr (nco > 0) {
                for (int k = 0; k < nco; ++k) v[k] = odg[k * ng + i];
            }
            if constexpr (ncw > 0) {
                for (int k = 0; k < ncw; ++k) w[k] = wdg[k * ng + i];
            }

            // Value
            double f_local[ncu * nd];
            M::flux(f_local, x, uq, v, w, param, /*uinf=*/nullptr, t);
            for (int k = 0; k < ncu * nd; ++k) f[k * ng + i] = f_local[k];

            // ∂f/∂uq
            double f_uq[ncu * nd * Nq];
            M::flux_jac_uq(f_uq, x, uq, v, w, param, /*uinf=*/nullptr, t);
            for (int k = 0; k < ncu * nd * Nq; ++k) f_udg[k * ng + i] = f_uq[k];

            // ∂f/∂w (only when present)
            if constexpr (ncw > 0) {
                double f_w[ncu * nd * ncw];
                M::flux_jac_w(f_w, x, uq, v, w, param, /*uinf=*/nullptr, t);
                for (int k = 0; k < ncu * nd * ncw; ++k) f_wdg[k * ng + i] = f_w[k];
            }
        });
}

} // namespace exasim
