// Auto-generated by apps/library_example/port_codegen.sh.
// Generic facade-driven main: reuses every codegen example's
// `pdeapp.txt` + `my_model.hpp` but routes through `ExasimSolver<M>`
// instead of `exasim::run<M>(argc, argv)`.
//
// Builds for cpu / gpu / mpi / mpi_gpu via the same compile-time
// `_MPI` / `_CUDA` / `_HIP` defines the legacy `_codegen*` targets
// use. CMake target shape:
//   <name>_facade            cpu
//   <name>_facade_gpu        gpu
//   <name>_facade_mpi        mpi
//   <name>_facade_mpi_gpu    mpi+gpu
//
// Tutorial: doc/tutorial_cpu_gpu_mpi.md §3.

#include <exasim/run.hpp>             // pulls preamble + backend headers
#include <exasim/model.hpp>
#include <exasim/solver_facade.hpp>

#include "my_model.hpp"

#include <fstream>

int main(int argc, char** argv) {
    int mpiprocs = 1, mpirank = 0, shmrank = 0;
#ifdef HAVE_MPI
    MPI_Init(&argc, &argv);
    EXASIM_COMM_WORLD = MPI_COMM_WORLD;
    EXASIM_COMM_LOCAL = MPI_COMM_WORLD;
    MPI_Comm_size(EXASIM_COMM_WORLD, &mpiprocs);
    MPI_Comm_rank(EXASIM_COMM_WORLD, &mpirank);
    MPI_Comm shmcomm;
    MPI_Comm_split_type(EXASIM_COMM_WORLD, MPI_COMM_TYPE_SHARED, 0,
                        MPI_INFO_NULL, &shmcomm);
    MPI_Comm_rank(shmcomm, &shmrank);
#else
    (void)shmrank;
#endif

#ifdef HAVE_CUDA
    int nd; cudaGetDeviceCount(&nd); cudaSetDevice(shmrank % nd);
#endif
#ifdef HAVE_HIP
    int nd; hipGetDeviceCount(&nd); hipSetDevice(shmrank % nd);
#endif

    if (argc < 2) {
        if (mpirank == 0) std::cerr << "Usage: " << argv[0] << " <pdeapp.txt>\n";
#ifdef HAVE_MPI
        MPI_Finalize();
#endif
        return 1;
    }

    Kokkos::initialize();
    {
        exasim::ExasimSolver<GeneratedModel> solver;
        solver.load_pdeapp(argv[1], mpirank);
        // The codegen baseline writes outudg_np<r>.bin etc. — keep
        // those on so validate_codegen.sh's bin-md5 / qoi gates work.
        solver.pde().saveOutputs = 1;
        solver.solve(mpiprocs, mpirank);
    }
    Kokkos::finalize();

#ifdef HAVE_MPI
    MPI_Finalize();
#endif
    return 0;
}
